# HTTP
quarkus.http.port=8080

# Redis
quarkus.redis.hosts=redis://localhost:6379

# JSON
quarkus.jackson.fail-on-unknown-properties=true

# Dev
quarkus.log.level=INFO
quarkus.log.category."com.burnout.dixit".level=DEBUG
